### ISSUE TITLE
[Suggestion] Find New Procedure Location > After current procedure

### ISSUE THREAD

**Issue by fvet** [DavidFeldhoff/al-codeactions#123]
When refactoring functions (split in atomic / helper functions), I often want my new functions to be close to it's parent function. It would be nice if we could either have a new 'Find New Procedure Location' option 'After current procedure' (only applies for refactored code in procedures, make no real sense for refactoring table / field / page trigger code)

Alternative might be to add the current procedure (if any) as the **first** available option in the list when you would use 'Always Ask'.?

![image](https://user-images.githubusercontent.com/25268332/127109154-3a3505c7-ff5c-4605-acd8-a5340877e5e4.png)

**Comment by DavidFeldhoff** [comment]
Hi Frédéric,
I think I get your point thanks for reaching out. But what should happen differently if I add a procedure inside or extract some code out of a table field trigger? Should it be added by type, access modifier and name/range? That would be quite implicit and intransparent which I generally do not like, but I don't like the alternative either that it would be added as first procedure, just because it's the nearest position to the table field.
Maybe your alternative solution with the "always ask" option is therefore more straight forward and transparent..

**Comment by fvet** [comment]
Most transparent (covering both scenarios) would be indeed extending the 'Alwask Ask' option by adding the **current** procedure (when applicable) as the first in the list (maybe suffix with _(Current)_), so we can simply confirm the new procedure location with **Enter**.

**Comment by DavidFeldhoff** [comment]
This is also included in the last release v1.0.7. I hope it solves your requirements?

**Comment by jwikman** [comment]
> This is also included in the last release v1.0.7. I hope it solves your requirements?

Well done @DavidFeldhoff!
I was just about to report a feature suggestion about this, luckely I used the search function first. This fulfilled my request, thanks!

**Comment by DavidFeldhoff** [comment]
Thanks for the feedback and I'm glad it fulfills your requirements 😊 often the positive feedback comes a bit short, so thanks for that 👌🏻

**Comment by fvet** [comment]
![image](https://user-images.githubusercontent.com/25268332/140337475-cf20523a-0c86-47ba-9712-736ff9064de5.png)
