### ISSUE TITLE
Make a variable global: is this really good?

### ISSUE THREAD

**Issue by JalmarazMartn** [DavidFeldhoff/al-codeactions#142]
Good evening, I love your extension, but i Don´t like this action, "Make a variable global". I realized just today that this exists. In a world when people tell all the time to avoid global variables, "be as local as you can", "avoid side efects", is necesary or simply good to offer turn a local variable in a global one?

In my opinion this ease a bad practice.

Best regards and thanks for your extension.

**Comment by DavidFeldhoff** [comment]
Good evening and thanks for the feedback!
I agree with you that code should be as local as possible. Especially if the variables are stateful! That's always a big warning for me. 

But if it's a stateless CodeUnit, I don't see why that shouldn't be global. Let's take the "Library - Assert" as example. Why should I create that in each of my test procedures? That doesn't make sense. I'm just creating multiple instances of a CodeUnit which consumes memory which is stateless anyway.

That's at least my viewing point. I'm with you that it shouldn't be used all the time. If a developer makes generally everything public - that's what code reviews are for ;)
And of course if you don't like it, you don't have to use it. But I won't remove the possibility due to the reasons I explained above. I hope you can follow my explanation. 

Wish you a great evening and all the best
David

**Comment by DavidFeldhoff** [comment]
The only thing I could do for you would be to add a setting that turns off the code action, so that you could set it in your workspace files and therefore deactivate it for your team colleagues as well, but as I said: there are reasons that variables can still be global and your colleagues could move the local variable manually as well, so it wouldn't make a difference in my eyes.

**Comment by JalmarazMartn** [comment]
David, thank you for your response. Close the issue if you want. You feel
that is necessary from your experience, and is all that actually matters. I
only wanted to know the reason for this action code.

About test code, partially agree, because in my test codeunits I declare
libraries as global too. But I think it is a very especifique example, an
exception.

Also I think that it is very curious that we consider an object stateless
and safe to declare as global... if it hasn't global variables inside.

Forgive me, I love these coding discussions and don`t want to steal your
time. Have a nice weekend!
