### ISSUE TITLE
Poor performance on big al file

### ISSUE THREAD

**Issue by xdimidrolx** [DavidFeldhoff/al-codeactions#180]
Hi!

First of all, I want to thank you for the cool extension, I use it a lot. 

Now I am faced with the issue within the big .al file.  I notice if the file has 4000+ lines the bulb button does not appear, or appears in a while approx 20-30+ sec. 

My PC 
<img width="188" alt="image" src="https://github.com/user-attachments/assets/6c183822-fb31-4c4f-b3d2-51d5852ac4ce">
<img width="385" alt="image" src="https://github.com/user-attachments/assets/0ae61d45-947d-450b-a884-d3b4d4460bad">

Please let me know if you need more details. 
Please advise how the performance could be improved.

**Comment by DavidFeldhoff** [comment]
Hi, 
I'm aware that it get's slower in bigger files/projects. But there's not much I can or want to do about. I'm simply parsing the file using the AL compiler to get the syntax tree and that is what takes time. 

To get a final solution I only see two options:
1. Microsoft would give us access to the syntax tree, so that there's no re-parsing needed, but that's not going to happen as multiple AL extension developers already asked for it.
2. I would have to create my own parser which is 1. a lot of work, 2. error-prone and 3. quite a lot of maintenance as the AL language evolves as well. That's why I'm not going down that road as well.

So I'm afraid I don't have *the* answer for you, but as you're asking for advise, I can try to give a few suggestions:
- One obvious advise would be to split down the codeunit as in such big files there's anyway a great chance that the Single Responsipility Principle isn't respected, but as that's quite obvious I think that's a poor advise.
- Another idea might be to try out to turn off the code action-lightbulbs. You can do that using the `editor.lightbulb.enabled: "off"` setting. The reason: Each time you place the cursor somewhere in your code, all code action providers (not just mine) are triggered to see if they have something to offer, so that VS Code is able to show the lightbulb. Obviously that might slow down the performance in general. When turning it off, you avoid these mostly unnecessary calculations, but you could still execute the codeaction or "ask" for codeactions by pressing `Ctrl + .`. Then code action providers are only executed explicitly which might improve the overall performance. Would be curious if that helps you.

/David

**Comment by xdimidrolx** [comment]
hi @DavidFeldhoff 
Thank you for the response and the advice. 
I guess that editor.lightbulb.enabled: "off" is something that might help me, I will try to use it... 

Br, 
Dmytro
