### ISSUE TITLE
Quickfix for interface

### ISSUE THREAD

**Issue by TKapitan** [DavidFeldhoff/al-codeactions#24]
Hi,
A new quick fix to generate the body of CU that implements an interface (with all procedures). In my current project, I have already 6 interfaces for enums and this is one of the things that I really miss

![image](https://user-images.githubusercontent.com/37966300/79743366-c1a2c800-8304-11ea-875d-e95d95424fb1.png)

( https://github.com/waldo1001/crs-al-language-extension/issues/165 )

**Comment by DavidFeldhoff** [comment]
Hi, if I understand you correctly, you want to insert the procedure stubs which are required by the interface.
This code action does already exist in the al language extension as stated in their [changelog](https://marketplace.visualstudio.com/items/ms-dynamics-smb.al/changelog), but you have to activate it.
I hope it helps and fits your needs. If there's something missing, please let me know, so that I could check if I can do something for you.

![image](https://user-images.githubusercontent.com/53570297/79765212-9d57e300-8326-11ea-8892-1c902c04cdcc.png)

![image](https://user-images.githubusercontent.com/53570297/79765266-aba5ff00-8326-11ea-9664-4566e765af60.png)

![image](https://user-images.githubusercontent.com/53570297/79765310-b95b8480-8326-11ea-83ba-4bda657c701a.png)

**Comment by waldo1001** [comment]
I think I showed this feature in my webinar without knowing it was part of your extension... my apologies .. :(.  And thanks for adding it!

**Comment by DavidFeldhoff** [comment]
Which feature do you mean? The "Implement interface" one?
That's not from me, that's from Microsoft, but you have to activate it in the settings of the "al language" extension :)

**Comment by waldo1001** [comment]
Ah, ok, I thought it was yours :-)
#confused
