### ISSUE TITLE
Create unknown procedures as event publishers

### ISSUE THREAD

**Issue by NKarolak** [DavidFeldhoff/al-codeactions#50]
My suggestions are based on my personal need only; probably they should be controlled by settings instead:
- If the unknown procedure name starts with keyword "On" + any _capital_ letter, then decorate the new procedure with `[IntegrationEvent(false, false)]`
- Put the new method at the very bottom, where usually all event publishers are gathered

**Comment by DavidFeldhoff** [comment]
Let me see what I can do for you :)

**Comment by DavidFeldhoff** [comment]
I think I found a way with the newest release. Thanks for posting the idea, I think it's really a nice feature! https://twitter.com/FeldhoffDavid/status/1265376816581222400
If the procedure starts with "On.." you can choose if you want to create a procedure for that or if you choose a publisher for an integration or business event. The preffered fix is then the integration event publisher, so that there's no setting necessary, I think.
Furthermore the cursor won't jump to the position as you can't add code to the publisher anyway and it's also placed in the right place in respect to Andrzej's "Sort procedures" :)

**Comment by NKarolak** [comment]
Thank you soooo much, really appreciated 👍
