### ISSUE TITLE
Extract to procedure: local variable is not removed from original parenting function

### ISSUE THREAD

**Issue by lvanvugt** [DavidFeldhoff/al-codeactions#92]
When extracting a function it nicely includes local variables from its original parenting function in the newly created procedure.
But unfortunately it leaves it declaration behind if it's no longer used there.

Can this be fixed?

**Comment by DavidFeldhoff** [comment]
Hi Luc, thanks for participating. It's currently by design if you want to use them afterwards. Abs I didn't want to pop up each time a message. But I'll think about what can be done or if a setting will make sense.
And I have to find time because I'm currently working on another awesome project called ATDD. Maybe you've heard of it ;)

**Comment by DavidFeldhoff** [comment]
I decided to remove the local ones as well. For adding variables again there is the AL Navigator Extension, so I think your suggestion is the better one ;)
I'll release it in a few days

**Comment by DavidFeldhoff** [comment]
In the last version it's released. Feel free to test and close it afterwards :)

**Comment by lvanvugt** [comment]
How long does it take before it's on the Gallery?

**Comment by DavidFeldhoff** [comment]
Just a few minutes. Here you can already see it (v0.2.20)
https://marketplace.visualstudio.com/items?itemName=davidfeldhoff.al-codeactions
Hope you can wait another 5 minutes :)

**Comment by lvanvugt** [comment]
Tested and OK.
